package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog", catalog = "salesystem")
public class Blog implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String title;
	private String content;
	private Date dateCreate;
	private Set<CommentBlog> commentBlogs = new HashSet<CommentBlog>(0);
	private Set<ImageBlog> imageBlogs = new HashSet<ImageBlog>(0);

	public Blog() {
	}

	public Blog(Account account, String title, String content, Date dateCreate) {
		this.account = account;
		this.title = title;
		this.content = content;
		this.dateCreate = dateCreate;
	}

	public Blog(Account account, String title, String content, Date dateCreate, Set<CommentBlog> commentBlogs,
			Set<ImageBlog> imageBlogs) {
		this.account = account;
		this.title = title;
		this.content = content;
		this.dateCreate = dateCreate;
		this.commentBlogs = commentBlogs;
		this.imageBlogs = imageBlogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_create", nullable = false, length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blog")
	public Set<CommentBlog> getCommentBlogs() {
		return this.commentBlogs;
	}

	public void setCommentBlogs(Set<CommentBlog> commentBlogs) {
		this.commentBlogs = commentBlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blog")
	public Set<ImageBlog> getImageBlogs() {
		return this.imageBlogs;
	}

	public void setImageBlogs(Set<ImageBlog> imageBlogs) {
		this.imageBlogs = imageBlogs;
	}

}
