package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caterogy generated by hbm2java
 */
@Entity
@Table(name = "caterogy", catalog = "salesystem")
public class Caterogy implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<ProductType> productTypes = new HashSet<ProductType>(0);

	public Caterogy() {
	}

	public Caterogy(String name) {
		this.name = name;
	}

	public Caterogy(String name, Set<ProductType> productTypes) {
		this.name = name;
		this.productTypes = productTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caterogy")
	public Set<ProductType> getProductTypes() {
		return this.productTypes;
	}

	public void setProductTypes(Set<ProductType> productTypes) {
		this.productTypes = productTypes;
	}

}
