package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CommentBlog generated by hbm2java
 */
@Entity
@Table(name = "comment_blog", catalog = "salesystem")
public class CommentBlog implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Blog blog;
	private String content;
	private String image;
	private Set<RepCommentBlog> repCommentBlogs = new HashSet<RepCommentBlog>(0);

	public CommentBlog() {
	}

	public CommentBlog(Account account, Blog blog, String content, String image) {
		this.account = account;
		this.blog = blog;
		this.content = content;
		this.image = image;
	}

	public CommentBlog(Account account, Blog blog, String content, String image, Set<RepCommentBlog> repCommentBlogs) {
		this.account = account;
		this.blog = blog;
		this.content = content;
		this.image = image;
		this.repCommentBlogs = repCommentBlogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_blog", nullable = false)
	public Blog getBlog() {
		return this.blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "image", nullable = false, length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commentBlog")
	public Set<RepCommentBlog> getRepCommentBlogs() {
		return this.repCommentBlogs;
	}

	public void setRepCommentBlogs(Set<RepCommentBlog> repCommentBlogs) {
		this.repCommentBlogs = repCommentBlogs;
	}

}
