package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CommentProduct generated by hbm2java
 */
@Entity
@Table(name = "comment_product", catalog = "salesystem")
public class CommentProduct implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Product product;
	private String content;
	private String image;
	private Set<RepcommentProduct> repcommentProducts = new HashSet<RepcommentProduct>(0);

	public CommentProduct() {
	}

	public CommentProduct(Account account, Product product) {
		this.account = account;
		this.product = product;
	}

	public CommentProduct(Account account, Product product, String content, String image,
			Set<RepcommentProduct> repcommentProducts) {
		this.account = account;
		this.product = product;
		this.content = content;
		this.image = image;
		this.repcommentProducts = repcommentProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "image", length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commentProduct")
	public Set<RepcommentProduct> getRepcommentProducts() {
		return this.repcommentProducts;
	}

	public void setRepcommentProducts(Set<RepcommentProduct> repcommentProducts) {
		this.repcommentProducts = repcommentProducts;
	}

}
