package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Coppon generated by hbm2java
 */
@Entity
@Table(name = "coppon", catalog = "salesystem", uniqueConstraints = @UniqueConstraint(columnNames = "code_sale"))
public class Coppon implements java.io.Serializable {

	private Integer id;
	private String name;
	private String content;
	private String codeSale;
	private Date datestart;
	private Date deadline;
	private boolean status;
	private Set<Order> orders = new HashSet<Order>(0);

	public Coppon() {
	}

	public Coppon(String codeSale, boolean status) {
		this.codeSale = codeSale;
		this.status = status;
	}

	public Coppon(String name, String content, String codeSale, Date datestart, Date deadline, boolean status,
			Set<Order> orders) {
		this.name = name;
		this.content = content;
		this.codeSale = codeSale;
		this.datestart = datestart;
		this.deadline = deadline;
		this.status = status;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "code_sale", unique = true, nullable = false, length = 50)
	public String getCodeSale() {
		return this.codeSale;
	}

	public void setCodeSale(String codeSale) {
		this.codeSale = codeSale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datestart", length = 10)
	public Date getDatestart() {
		return this.datestart;
	}

	public void setDatestart(Date datestart) {
		this.datestart = datestart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deadline", length = 10)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coppon")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
