package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "salesystem")
public class Employee implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String name;
	private boolean gender;
	private String mail;
	private String address;
	private Date birthday;
	private String phone;
	private String image;
	private boolean status;
	private Double salaryRatio;
	private Date dateJoin;
	private String cv;
	private String specialize;
	private Set<Order> orders = new HashSet<Order>(0);

	public Employee() {
	}

	public Employee(Account account, String name, boolean gender, String mail, String address, Date birthday,
			String phone, boolean status, Date dateJoin) {
		this.account = account;
		this.name = name;
		this.gender = gender;
		this.mail = mail;
		this.address = address;
		this.birthday = birthday;
		this.phone = phone;
		this.status = status;
		this.dateJoin = dateJoin;
	}

	public Employee(Account account, String name, boolean gender, String mail, String address, Date birthday,
			String phone, String image, boolean status, Double salaryRatio, Date dateJoin, String cv, String specialize,
			Set<Order> orders) {
		this.account = account;
		this.name = name;
		this.gender = gender;
		this.mail = mail;
		this.address = address;
		this.birthday = birthday;
		this.phone = phone;
		this.image = image;
		this.status = status;
		this.salaryRatio = salaryRatio;
		this.dateJoin = dateJoin;
		this.cv = cv;
		this.specialize = specialize;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", nullable = false)
	public boolean isGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

	@Column(name = "mail", nullable = false, length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "image", length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "salary_ratio", precision = 22, scale = 0)
	public Double getSalaryRatio() {
		return this.salaryRatio;
	}

	public void setSalaryRatio(Double salaryRatio) {
		this.salaryRatio = salaryRatio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_join", nullable = false, length = 10)
	public Date getDateJoin() {
		return this.dateJoin;
	}

	public void setDateJoin(Date dateJoin) {
		this.dateJoin = dateJoin;
	}

	@Column(name = "CV", length = 50)
	public String getCv() {
		return this.cv;
	}

	public void setCv(String cv) {
		this.cv = cv;
	}

	@Column(name = "specialize", length = 200)
	public String getSpecialize() {
		return this.specialize;
	}

	public void setSpecialize(String specialize) {
		this.specialize = specialize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
