package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EvaluateProduct generated by hbm2java
 */
@Entity
@Table(name = "evaluate_product", catalog = "salesystem")
public class EvaluateProduct implements java.io.Serializable {

	private Integer id;
	private InformationUser informationUser;
	private Product product;
	private Integer lever;
	private boolean status;

	public EvaluateProduct() {
	}

	public EvaluateProduct(InformationUser informationUser, Product product, boolean status) {
		this.informationUser = informationUser;
		this.product = product;
		this.status = status;
	}

	public EvaluateProduct(InformationUser informationUser, Product product, Integer lever, boolean status) {
		this.informationUser = informationUser;
		this.product = product;
		this.lever = lever;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_customer", nullable = false)
	public InformationUser getInformationUser() {
		return this.informationUser;
	}

	public void setInformationUser(InformationUser informationUser) {
		this.informationUser = informationUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "lever")
	public Integer getLever() {
		return this.lever;
	}

	public void setLever(Integer lever) {
		this.lever = lever;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
