package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "salesystem")
public class Feedback implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String title;
	private String content;
	private String email;
	private String phone;
	private Date datecreate;
	private String image;
	private String file;
	private boolean status;
	private Set<FeedbackRep> feedbackReps = new HashSet<FeedbackRep>(0);

	public Feedback() {
	}

	public Feedback(Account account, String title, String email, Date datecreate, String image, String file,
			boolean status) {
		this.account = account;
		this.title = title;
		this.email = email;
		this.datecreate = datecreate;
		this.image = image;
		this.file = file;
		this.status = status;
	}

	public Feedback(Account account, String title, String content, String email, String phone, Date datecreate,
			String image, String file, boolean status, Set<FeedbackRep> feedbackReps) {
		this.account = account;
		this.title = title;
		this.content = content;
		this.email = email;
		this.phone = phone;
		this.datecreate = datecreate;
		this.image = image;
		this.file = file;
		this.status = status;
		this.feedbackReps = feedbackReps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecreate", nullable = false, length = 10)
	public Date getDatecreate() {
		return this.datecreate;
	}

	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}

	@Column(name = "image", nullable = false, length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "file", nullable = false, length = 50)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedback")
	public Set<FeedbackRep> getFeedbackReps() {
		return this.feedbackReps;
	}

	public void setFeedbackReps(Set<FeedbackRep> feedbackReps) {
		this.feedbackReps = feedbackReps;
	}

}
