package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImageType generated by hbm2java
 */
@Entity
@Table(name = "image_type", catalog = "salesystem")
public class ImageType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<ImageProduct> imageProducts = new HashSet<ImageProduct>(0);

	public ImageType() {
	}

	public ImageType(String name) {
		this.name = name;
	}

	public ImageType(String name, Set<ImageProduct> imageProducts) {
		this.name = name;
		this.imageProducts = imageProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imageType")
	public Set<ImageProduct> getImageProducts() {
		return this.imageProducts;
	}

	public void setImageProducts(Set<ImageProduct> imageProducts) {
		this.imageProducts = imageProducts;
	}

}
