package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "salesystem")
public class OrderDetail implements java.io.Serializable {

	private Integer id;
	private Order order;
	private Product product;
	private Sale sale;
	private int quatity;
	private long price;
	private boolean status;

	public OrderDetail() {
	}

	public OrderDetail(Order order, Product product, int quatity, long price, boolean status) {
		this.order = order;
		this.product = product;
		this.quatity = quatity;
		this.price = price;
		this.status = status;
	}

	public OrderDetail(Order order, Product product, Sale sale, int quatity, long price, boolean status) {
		this.order = order;
		this.product = product;
		this.sale = sale;
		this.quatity = quatity;
		this.price = price;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_order", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sale")
	public Sale getSale() {
		return this.sale;
	}

	public void setSale(Sale sale) {
		this.sale = sale;
	}

	@Column(name = "quatity", nullable = false)
	public int getQuatity() {
		return this.quatity;
	}

	public void setQuatity(int quatity) {
		this.quatity = quatity;
	}

	@Column(name = "price", nullable = false, precision = 10, scale = 0)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
