package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name = "product_type", catalog = "salesystem")
public class ProductType implements java.io.Serializable {

	private Integer id;
	private Caterogy caterogy;
	private Store store;
	private String name;
	private Set<Product> products = new HashSet<Product>(0);

	public ProductType() {
	}

	public ProductType(Caterogy caterogy, Store store) {
		this.caterogy = caterogy;
		this.store = store;
	}

	public ProductType(Caterogy caterogy, Store store, String name, Set<Product> products) {
		this.caterogy = caterogy;
		this.store = store;
		this.name = name;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_caterogy", nullable = false)
	public Caterogy getCaterogy() {
		return this.caterogy;
	}

	public void setCaterogy(Caterogy caterogy) {
		this.caterogy = caterogy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_store", nullable = false)
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productType")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
