package entitis;
// Generated Jul 24, 2019 11:13:14 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RepcommentProduct generated by hbm2java
 */
@Entity
@Table(name = "repcomment_product", catalog = "salesystem")
public class RepcommentProduct implements java.io.Serializable {

	private Integer id;
	private Account account;
	private CommentProduct commentProduct;
	private String content;
	private String image;

	public RepcommentProduct() {
	}

	public RepcommentProduct(Account account, CommentProduct commentProduct) {
		this.account = account;
		this.commentProduct = commentProduct;
	}

	public RepcommentProduct(Account account, CommentProduct commentProduct, String content, String image) {
		this.account = account;
		this.commentProduct = commentProduct;
		this.content = content;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comment", nullable = false)
	public CommentProduct getCommentProduct() {
		return this.commentProduct;
	}

	public void setCommentProduct(CommentProduct commentProduct) {
		this.commentProduct = commentProduct;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "image", length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
